# Big thanks and love for using my plugins! ^^

#|--------------------------------------------------------------------------------------------------------------------|#
# Plugin: Marriage
# Author: https://www.mc-market.org/members/89497/
# Description: Plugin for in-game Marriage.
# Dependencies:
#   -> PLJRApi
#   -> PlaceholderAPI<Optional> (https://www.spigotmc.org/resources/placeholderapi.6245/)
#|--------------------------------------------------------------------------------------------------------------------|#

###############\
# MySQL Setup ##############################################################################################\
############### This is the most important part, as the plugin can not work without proper MySQL Database. # \
              ##############################################################################################  \
mysql:
  enabled: false #-> Should we use this database instead of the one configured in PLJRApi config.yml?
  host: "127.0.0.1"
  port: "3306"
  database: "db"
  username: "root"
  password: ""
#|--------------------------------------------------------------------------------------------------------------------|#

##################\
# Settings Setup #############################################################\
################## Here, you can enable or disable functions of this plugin. # \
                 #############################################################  \
settings:
  bungee: false #-> Should we use bungee functions?
  particles: true #-> Should we use particles?
  sounds: true  #-> Should we use sounds?
  shared-food: true #-> Should the sharing food be enabled?
  shared-xp: true #-> Should the sharing XP be enabled?
  toggle-pvp: true #-> Should the players be able to toggle pvp?
  toggle-food: true #-> Should the players be able to toggle food sharing?
  toggle-xp: true #-> Should the players be able to toggle xp sharing?
  menu: true #-> Should /marry open a GUI? (false = help message will be send instead)
  cost-marry: 7500 #-> How much should marrying someone cost?
  cost-divorce: 5000 #-> How much should divorcing someone cost?
  cooldown: 200 #-> How long should it take for marry request to get cancelled?
  default-pvp: false #-> Default PvP value for new players.
  default-food: true #-> Default food sharing value for new players.
  default-xp: true #-> Default XP sharing value for new players.
#|--------------------------------------------------------------------------------------------------------------------|#

######################
# Default Home Setup ################################################################################################
###################### Here, you can set the location of default home. # (I recommend setting it to server's spawn) #
                     ################################################################################################
defaulthome:
  world: "world"
  x: 0
  y: 70
  z: 0
  yaw: 0
  pitch: 0
#|--------------------------------------------------------------------------------------------------------------------|#

################\
# Sounds Setup #######################################################\
################ Here, you can customize sounds, made by the plugin. # \
               #######################################################  \
sounds:
  FAIL: "ENTITY_VILLAGER_NO"
  DIVORCE: "ITEM_SHIELD_BREAK"
  MENU_CLICK: "BLOCK_NOTE_BLOCK_PLING"
  MARRY_ACCEPT: "ENTITY_PLAYER_LEVELUP"
  NOTIFY: "ENTITY_EXPERIENCE_ORB_PICKUP"
#|--------------------------------------------------------------------------------------------------------------------|#

##############\
# Menu Setup ####################################################\
############## Here, you can customize the looks of Marry menu. # \
             ####################################################  \
menu:
  title: "§a§lMarriage"
  heart:
    type: "RED_STAINED_GLASS_PANE"
    name: "§c"
    amount: 1
  white:
    type: "WHITE_STAINED_GLASS_PANE"
    name: "§f"
    amount: 1
  background:
    type: "LIGHT_BLUE_STAINED_GLASS_PANE"
    name: "§f"
    amount: 1
  lastseen:
    type: "REDSTONE_LAMP"
    name: "§eLast seen"
    amount: 1
    lore:
      - "§8» §fClick to find out,"
      - " §fwhen your partner was"
      - " §flast seen on the server."
  sharedxpinfo:
    type: "EXPERIENCE_BOTTLE"
    name: "§eShared Experience"
    amount: 1
    lore:
      - "§8» §fGained XP are halved"
      - " §fand shared with your partner."
  tphome:
    type: "RED_BED"
    name: "§eHome Teleportation"
    amount: 1
    lore:
      - "§8» §fClick to be teleported to"
      - " §fyour shared home."
  gift:
    type: "CHEST"
    name: "§eGift"
    amount: 1
    lore:
      - "§8» §fClick to surprise your"
      - " §fpartner with a lovely gift!"
      - " §7(Will send your held item to"
      - " §7your partner)"
  tp:
    type: "ENDER_PEARL"
    name: "§eTeleportation"
    amount: 1
    lore:
      - "§8» §fClick to be teleported to"
      - " §fyour partner."
  pvp:
    type: "DIAMOND_SWORD"
    name: "§ePvP"
    amount: 1
    lore:
      - "§8» §fClick to turn ON/OFF your"
      - " §fPvP with partner."
  sethome:
    type: "WOODEN_DOOR"
    name: "§eSet Home"
    amount: 1
    lore:
      - "§8» §fClick to set your shared home"
      - " §fto your current location."
  sharedfoodinfo:
    type: "COOKED_PORKCHOP"
    name: "§eShared Food"
    amount: 1
    lore:
      - "§8» §fGained food is halved"
      - " §fand shared with your partner."
  privatechatinfo:
    type: "PAPER"
    name: "§eShared Chat"
    amount: 1
    lore:
      - "§8» §fClick to start writing"
      - " §fto your shared chat."
#|--------------------------------------------------------------------------------------------------------------------|#

##############\
# Lang Setup ################################################################\
############## Here, you can customize messages, send by the plugin itself. # \
             ################################################################  \
help:
  - ""
  - "§a§lMarriage Help v${project.version}"
  - ""
  - "§e/marry seen §8» §fChecks when your partner was last connected."
  - "§e/marry tp §8» §fTeleportation to your partner."
  - "§e/marry gift §8» §fGives currently held item to your partner."
  - "§e/marry sethome §8» §fSets your location as the current shared home."
  - "§e/marry home §8» §fTeleportation to your shared home."
  - "§e/marry chat <message> §8» §fSends message to shared private chat."
  - "§e/marry pvp §8» §fToggles your PvP with partner."
  - "§e/marry xp §8» §fToggles your XP Sharing with partner."
  - "§e/marry food §8» §fToggles your Food Sharing with partner."
  - "§e/marry list [page] §8» §fList of all married couples."
  - "§eStatus: §f%marriage_state%"
  - ""

admin-help:
  - ""
  - "§a§lMarriage Admin-Help v${project.version}"
  - ""
  - "§e/amarry spy §8» §fToggles displaying private chats of other players."
  - "§e/amarry marry <player> <player> §8» §fForces players to marry each other. §7(With no cost)"
  - "§e/amarry unmarry <player> §8» §fForces players to divorce. §7(With no cost)"
  - "§e/amarry sethome <player> §8» §fSets location as the current shared home for player."
  - "§e/amarry home <player> §8» §fTeleportation to player's shared home."
  - "§e/amarry pvp <player> §8» §fToggles player's PvP with partner."
  - "§e/amarry food <player> §8» §fToggles player's Food Sharing with partner."
  - "§e/amarry xp <player> §8» §fToggles player's XP Sharing with partner."
  - "§e/amarry reload §8» §fReloads the configuration. §7(Not recommended)"
  - ""

lang:
  NO_CONSOLE: "§cThis command is only for players!"
  NO_PARTNER: "§c§l❤ §aMarriage §8» §fYou don't have a partner!"
  ITEM_IN_HAND: "§c§l❤ §aMarriage §8» §fYou aren't holding any item!"
  GIFT_SEND: "§c§l❤ §aMarriage §8» §fYou've send a gift to §b%name§f."
  GIFT_RECEIVE: "§c§l❤ §aMarriage §8» §fYou received a gift from §b%name§f."
  TPHOME: "§c§l❤ §aMarriage §8» §bSuccessfully §fteleported to your shared home."
  SETHOME_PLAYER: "§c§l❤ §aMarriage §8» §bSuccessfully §fset a location for shared home."
  SETHOME_PARTNER: "§c§l❤ §aMarriage §8» §fYour partner set a new location for §bshared home§f."
  LASTSEEN: "§c§l❤ §aMarriage §8» §b%name §fwas last seen §b%time §fago."
  PVP_ON: "§c§l❤ §aMarriage §8» §fYou've §benabled §fyour PvP."
  PVP_OFF: "§c§l❤ §aMarriage §8» §fYou've §bdisabled §fyour PvP."
  PVP_ON_OTHERS: "§c§l❤ §aMarriage §8» §fYou've §benabled §fplayer's PvP."
  PVP_OFF_OTHERS: "§c§l❤ §aMarriage §8» §fYou've §bdisabled §fplayer's PvP."
  TELEPORT_PLAYER: "§c§l❤ §aMarriage §8» §bSuccessfully §fteleported to §b%name§f."
  TELEPORT_PARTNER: "§c§l❤ §aMarriage §8» §b%name §fhas been teleported to you."
  NO_MONEY: "§c§l❤ §aMarriage §8» §fYou don't have enough money! §7(§e$%cost§7)"
  DIVORCE_PLAYER_TITLE: "§cMarriage"
  DIVORCE_PLAYER_SUBTITLE: "§c✖ §fDivorced."
  DIVORCE_PARTNER_TITLE: "§cMarriage"
  DIVORCE_PARTNER_SUBTITLE: "§c✖ §fDivorced."
  DIVORCE_BROADCAST: "§c§l❤ §aMarriage §8» §b%name1 §fand §b%name2 §fwere divorced!"
  HAVE_PARTNER: "§c§l❤ §aMarriage §8» §fYou already have a §bpartner§f!"
  HAVE_PARTNER_PLAYER: "§c§l❤ §aMarriage §8» §fb%name §falready has a partner!"
  REQUEST_PENDING: "§c§l❤ §aMarriage §8» §fYou still have a §bpending §frequest!"
  REQUEST_PENDING_PLAYER: "§c§l❤ §aMarriage §8» §b%name §fhas a request pending§f!"
  MARRY_ACCEPT_PLAYER1_TITLE: "§c§l❤ §aMarriage §c§l❤"
  MARRY_ACCEPT_PLAYER1_SUBTITLE: "§fYou §baccepted §fa marry request from §b%name§f."
  MARRY_ACCEPT_PLAYER2_TITLE: "§c§l❤ §aMarriage §c§l❤"
  MARRY_ACCEPT_PLAYER2_SUBTITLE: "§b%name §f%accepted your marry request!"
  MARRY_ACCEPT_BROADCAST: "§c§l❤ §aMarriage §8» §b%name1 §fand §b%name2 §fwere married!"
  REQUEST_SEND: "§c§l❤ §aMarriage §8» §fYou've successfully send a request for marry to §b%name§f."
  REQUEST_RECEIVED: "§c§l❤ §aMarriage §8» §b%name §fsend you marry request."
  REQUEST_EXPIRED_SENDER: "§c§l❤ §aMarriage §8» §b%name §fdid not accept your marry request."
  REQUEST_EXPIRED_RECEIVER: "§c§l❤ §aMarriage §8» §fYou §bdeclined §fmarry request from §b%name§f."
  NO_NUMBER: "§c§l❤ §aMarriage §8» §b%arg §fis not a number!"
  GENDER_SET: "§c§l❤ §aMarriage §8» §fYou set your gender to §b%gender§f."
  NO_GENDER: "§c§l❤ §aMarriage §8» §b%gender §fis not a gender!"
  PARTNER_NO_PARTNER: "§c§l❤ §aMarriage §8» §b%name §fdoes not have a partner!"
  PARTNER: "§c§l❤ §aMarriage §8» §b%name's §fpartner is §b%partner§f."
  CHAT_FORMAT: "§4§l❤§c§l-Chat §a%name §8» §e%message"
  CHAT_FORMAT_SPY: "§7❤-Chat §c%name §7» §c%message"
  LIST_TITLE: "§c§l❤ §aMarriage §8» §fList of couples:"
  GENDER_MALE: "Male"
  GENDER_MALE_COLOR: "§b"
  GENDER_MALE_SYMBOL: "♀"
  GENDER_FEMALE: "Female"
  GENDER_FEMALE_COLOR: "§d"
  GENDER_FEMALE_SYMBOL: "♂"
  GENDER_NONE: "None"
  GENDER_NONE_COLOR: "§7"
  GENDER_NONE_SYMBOL: "●"
  KISS_PLAYER: "§c§l❤ §aMarriage §8» §bYou §fkissed §b%name§f."
  KISS_PARTNER: "§c§l❤ §aMarriage §8» §b%name §fhas kissed you."
  CLICK_TO_DIVORCE: "§8» §fClick for divorce."
  CHAT_USAGE: "§c§l❤ §aMarriage §8» §bUsage: §f/marry c <text>"
  ONLINE: "§c§l❤ §aMarriage §8» §b%name §fis on the server."
  STATE_SINGLE: "Single"
  STATE_MARRIED: "Married"
  PVP_ENABLED: "On"
  PVP_DISABLED: "Off"
  SPY_ACTIVE: "§c§l❤ §aMarriage §8» §bSpy §factivated."
  SPY_UNACTIVE: "§c§l❤ §aMarriage §8» §bSpy §fdeactivated."
  FOOD_ON: "§c§l❤ §aMarriage §8» §fYou've §benabled §fFood sharing."
  FOOD_OFF: "§c§l❤ §aMarriage §8» §fYou've §bdisabled §fFood sharing."
  FOOD_ON_OTHERS: "§c§l❤ §aMarriage §8» §fYou've §benabled §fplayer 's food sharing."
  FOOD_OFF_OTHERS: "§c§l❤ §aMarriage §8» §fYou've §bdisabled §fplayer 's food sharing."
  XP_ON: "§c§l❤ §aMarriage §8» §fYou've §benabled §fXP sharing."
  XP_OFF: "§c§l❤ §aMarriage §8» §fYou've §bdisabled §fXP sharing."
  XP_ON_OTHERS: "§c§l❤ §aMarriage §8» §fYou've §benabled §fplayer 's xp sharing."
  XP_OFF_OTHERS: "§c§l❤ §aMarriage §8» §fYou've §bdisabled §fplayer 's xp sharing."
  FOOD_ACTIONBAR: "§c§l❤ §aMarriage §8» §fYou received §b%amount §ffood."
  XP_ACTIONBAR: "§c§l❤ §aMarriage §8» §fYou received §b%amount §fXP."
  RELOAD_FINISHED: "§c§l❤ §aMarriage §8» §fReload §bsuccessful§f."
#|--------------------------------------------------------------------------------------------------------------------|#