# Big thanks and love for using my plugins! ^^

#|--------------------------------------------------------------------------------------------------------------------|#
# Plugin: Marriage
# Author: https://www.mc-market.org/members/89497/
# Description: Plugin for in-game Marriage.
# Dependencies:
#   -> PLJRApi-Spigot
#   -> PlaceholderAPI<Optional> (https://www.spigotmc.org/resources/placeholderapi.6245/)
#|--------------------------------------------------------------------------------------------------------------------|#

###############\
# MySQL Setup ##############################################################################################\
############### This is the most important part, as the plugin can not work without proper MySQL Database. # \
              ##############################################################################################  \
mysql:
  enabled: false #-> Should we use this database instead of the one configured in PLJRApi config.yml?
  host: "127.0.0.1"
  port: "3306"
  database: "db"
  username: "root"
  password: ""
#|--------------------------------------------------------------------------------------------------------------------|#

##################\
# Settings Setup #############################################################\
################## Here, you can enable or disable functions of this plugin. # \
                 #############################################################  \
settings:
  bungee: false #-> Should we use bungee functions?
  particles: true #-> Should we use particles?
  sounds: true  #-> Should we use sounds?
  toggle-pvp: true #-> Should the players be able to toggle pvp?
  toggle-food: true #-> Should the players be able to toggle food sharing?
  toggle-xp: true #-> Should the players be able to toggle xp sharing?
  menu: true #-> Should /marry open a GUI? (false = help message will be send instead)
  cost-marry: 7500 #-> How much should marrying someone cost?
  cost-divorce: 5000 #-> How much should divorcing someone cost?
  cache-players: true #-> Should we save player data in memory? (false = loading on each join)
#|--------------------------------------------------------------------------------------------------------------------|#