name: Marriage
version: ${project.version}
main: me.pljr.marriage.Marriage
api-version: 1.13
authors: [9hx]
description: Plugin for in-game Marriage.
depend: [Vault]
softdepend: [PlaceholderAPI]

commands:
  marry:
    description: Main command.
  amarry:
    description: Main admin command.
