name: Marriage
version: ${project.version}
main: me.pljr.marriage.Marriage
api-version: 1.13
authors: [9hx]
description: Plugin for in-game Marraige.
depend: [Vault]
softdepend: [PlaceholderAPI]

commands:
  marry:
    description: Hlavný príkaz.
